language: node_js
node_js:
- 15
before_install:
- npm install -g npm@latest
- npm install -g codecov
install:
- npm install --dev
script:
- npm test
after_success:
- npm run coverage
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: main
  skip_cleanup: 'true'
