language: node_js
node_js:
- 15
before_install:
- npm install -g npm@latest
- npm install -g codecov
install:
- npm install --dev
script:
- npm test
after_success:
- npm run coverage
deploy:
  provider: npm
  email: adamjonas25@gmail.com
  api_key:
    secure: Zx1aIDX9KYSeHq7ZT7tx6ogxmW6W/PxGZwgdp3U14xzczKv89bheaiYYWaqrI/RHAKGM9g3hr93hXsrZUlwfaMUTPXaUP9B4vB7TVeXymzSDHRz0Gn5IoRmpjcaUhQSy5ySMyg2ZxYkT0WbUOT0rfKYFXWORqQsDy8T93mxhCGNZv0bgVmzbfx9LNwr776XeN4sLJD69M83TPCVeTUnmkWyN6uxAz2WASI7gJj1xzDuY96cw/BzRR3njukdzR9r+OGnvk7tz/c4SCXbjEXeHMouFknRj/hnZy8GjjrQHJDAAoECZuzUc7O2vDXmOYkaISDIUPVxsdHhdJMZYE+WuHCJmJz1sxh1cPLy447iDJ0+hgMAA6IkfvWWZhrC+ETLjKN5oQqarnpz7txRoIXRHdQzkCSRdrA4iXcoj6iWIh0hdtGmzJE0xiszmttpKIDd5xQlKPRn18D8H7IccgMP/VudId9zAsMvfJzVLczoj9hpN/Cc6UhXhiiVukCEubWmRbzuBGKkGvSudmap5MYaxVgylxD3WdMNmQIAU67HjxPg5gKYdsTiZSK68SIrUfjQA32eRAbnV0jiUR5mlMf8XlrTmZNXRVjP2pD1NsbLX8l4/+IWOYCAyF2y8BsyWJcNxsGzAZ5KYaqHob0bil0IyZj1rXM2R76u1QfFwZfIp49s=
  on:
    repo: AJ8GH/code-timer
    branch: main
  skip_cleanup: 'true'
